### PR TITLE
fix: the rustup update caused an error

### LINKED ISSUE #29: proc_macro::Span Obtaining error
active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.72.0-nightly (839e9a6e1 2023-07-02)

The rustup update caused an error.

TJ N~W5~C8MSL}D)(6AA_ X

### PR DESCRIPTION
**Pull request by luoxiaozero**
Fixes #29 .
Merging this branch results in a nightly minimum requirement of 1.72.0.

### CODE REVIEW

**Comment by abishekatp** [comment]
Thank you for the pull request I will check this out and merge.

**Comment by scdailey** [comment]
Status on the merge for this PR?

**Comment by abishekatp** [comment]
Sorry It has been busy week. Thank you for you patience. I will merge and release it today.

**Comment by scdailey** [comment]
No worries, thank you both!

**Pull request merged**
